Выполнил задания по 3 модулю
js-tasks-ru/jsbasic-20220418-2_twin pull request #4
Opened 2022-04-25 19:08 UTC by TripToTokyo

2022-04-25 19:09 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-26 10:23 UTC, SinimaWath requested changes

2022-04-26 10:23 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  users.forEach((user) => result.push(user.name));
Давай тут используем map

2022-04-26 10:23 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return newStr.join('');
Давай тут попробуем -> filter -> map -> join

2022-04-26 15:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-27 08:18 UTC, SinimaWath approved these changes

2022-04-27 08:20 UTC, merged